<?php

namespace migrations;

require_once __DIR__ .'/lib.inc.php';

// Write you code here
//
// You can use
// db_query('some sql');  for quering
// db_pdo()->...;         some pdo functions

db_query(<<<SQL
CREATE TABLE IF NOT EXISTS `menu` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `label` varchar(255) COLLATE utf8_polish_ci DEFAULT NULL,
  `path` varchar(255) COLLATE utf8_polish_ci DEFAULT NULL,
  `icon` varchar(255) COLLATE utf8_polish_ci DEFAULT NULL,
  `rel` varchar(255) COLLATE utf8_polish_ci DEFAULT NULL,
  `parent_id` int(11) DEFAULT NULL,
  `activate-routes` varchar(255) COLLATE utf8_polish_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;
INSERT INTO `menu` (`id`, `label`, `path`, `icon`, `rel`, `parent_id`, `activate-routes`) VALUES
(1, 'Strona główna', '/home', 'icon-home', 'home', NULL, NULL),
(2, 'Komunikacja', 'javascript:;', 'icon-chat-1', 'messages', NULL, NULL),
(3, 'Pracownicy', 'javascript:;', 'fa fa-users', 'people', NULL, NULL),
(4, 'Dokumenty', 'javascript:;', 'icon-book-open-1', 'documents', NULL, NULL),
(5, 'Zamówienia publiczne', '/public-procurements', 'icon-archive', 'public', NULL, NULL),
(6, 'Zbiory', 'javascript:;', 'icon-archive', 'store', NULL, NULL),
(7, 'Raporty', '/reports', 'icon-print', 'report', NULL, NULL),
(8, 'Rejestry', '/registry', 'glyphicon glyphicon-th-large', 'report', NULL, 'registry-entries'),
(9, 'Zasoby Informatyczne', 'javascript:;', 'fa fa-floppy-o', 'informatyk', NULL, NULL),
(10, 'Czynności przetwarzania', 'javascript:;', 'glyphicon glyphicon-transfer', 'data_transfers', NULL, NULL),
(11, 'Analiza ryzyka', 'javascript:;', 'glyphicon glyphicon-transfer', 'data_transfers', NULL, NULL),
(12, 'Dane rejestracji', 'javascript:;', 'glyphicon glyphicon-dashboard', 'data_transfers', NULL, NULL),
(13, 'Szkolenia', 'javascript:;', 'fa fa-graduation-cap', 'data_transfers', NULL, NULL),
(14, 'Podpisy', '/signatures', 'fa fa-bank', 'home', NULL, NULL),
(15, 'Przeglądy', '/inspections', 'fa fa-calendar-check-o', 'home', NULL, NULL),
(16, 'Dysk online', '/file-sources', 'fa fa-file', 'home', NULL, NULL),
(17, 'Zdarzenia', 'javascript:;', 'icon-shuffle-2', 'events', NULL, NULL),
(18, 'Zadania', '/tasks', 'glyphicon glyphicon-tasks', 'tasks', NULL, NULL),
(19, 'Aplikacja', 'javascript:;', 'icon-wrench', 'configuration', NULL, NULL),
(20, 'Profil', 'javascript:;', 'icon-user', 'profile', NULL, NULL),
(21, 'Wiadomości', '/messages', 'icon-mail-2', 'messages', 2, NULL),
(22, 'Komunikaty', '/kominfoadm', 'icon-website', 'admin', 2, NULL),
(23, 'Zgłoszenia', '/tickets', 'fa fa-umbrella', 'tickets', 2, NULL),
(24, 'Moje zadania', '/tasks-my', 'icon-th-thumb-empty', 'tasks', 2, NULL),
(25, 'Rejestr Osób', '/osoby', 'fa fa-users', 'people', 3, NULL),
(26, 'Uprawnienia', '/permissions', 'fa fa-users', 'people', 3, NULL),
(27, 'Konta bankowe', '/osoby/kontabankowe', 'glyphicon glyphicon-usd', 'people_bankaccounts', 3, NULL),
(28, 'Podpisy elektroniczne', '/osoby/podpisy', 'glyphicon glyphicon-pencil', 'people_signs', 3, NULL),
(29, 'Inne osoby', '/osoby-inne', 'fa fa-users', 'people', 3, NULL),
(30, 'Grupy osób', '/groups', 'fa fa-list-ol', 'groups', 3, NULL),
(31, 'Dokumenty wersjonowane', '/documents-versioned', 'icon-docs', 'documents_versioned', 4, NULL),
(32, 'Dokumentacja osobowa', '/documents', 'icon-book-open-1', 'documents', 4, NULL),
(33, 'Wszystkie dokumenty', '/documents/all', 'icon-box-1', 'documents_all', 4, NULL),
(34, 'Dokumenty oczekujące', '/documents/pending', 'fa fa-clock-o', 'documents', 4, NULL),
(35, 'Szablony dokumentów', '/documenttemplates', 'fa fa-file-o', 'documenttemplates', 4, NULL),
(36, 'Schematy numeracji', '/numberingschemes', 'fa fa-sort-numeric-asc', 'numberingschemes', 4, NULL),
(37, 'Rejestr zbiorów', '/zbiory', 'icon-archive', 'store', 6, NULL),
(38, 'Rejestr zbiorów GIODO', '/giodo', 'icon-upload-3', 'giodo', 6, NULL),
(39, 'Rejestry publiczne', '/public-registry', 'icon-archive', 'public', 6, NULL),
(40, 'Systemy teleinformacyjne', '/systemy-teleinformacyjne', 'icon-archive', 'public', 6, NULL),
(41, 'Elementy zbioru', '/fielditems', 'fa fa-book', 'store', 6, NULL),
(42, 'Pola', '/fields', 'icon-th-list-1', 'store', 6, NULL),
(43, 'Podmioty', '/persons', 'icon-users', 'store', 6, NULL),
(44, 'Akty prawne', '/legalacts', 'icon-section-sign', 'store', 6, NULL),
(45, 'Zabezpieczenia', '/zabezpieczenia', 'icon-key-inv', 'saferules', 6, NULL),
(46, 'Pomieszczenia i budynki', '/pomieszczenia', 'icon-home-circled', 'pomieszczenia', 6, NULL),
(47, 'Partnerzy', '/contacts', 'icon-users', 'contacts', 6, NULL),
(48, 'Typy osób', '/persontypes', 'icon-cc-by', 'store', 6, NULL),
(49, 'Kategorie elementów', '/fielditemscategories', 'icon-folder-empty-1', 'store', 6, NULL),
(50, 'Kategorie pól', '/fieldscategories', 'fa fa-list-ol', 'store', 6, NULL),
(51, 'Rejestr zmian w zbiorach', '/zbiory-changelog', 'fa fa-list-ol', 'store', 6, NULL),
(52, 'Rejestr rozmów', '/registry-phone-calls', 'glyphicon glyphicon-earphone', 'registry_phone_calls', 8, NULL),
(53, 'Wykaz aplikacji', '/aplikacje', 'icon-clipboard', 'application', 9, NULL),
(54, 'Wykaz modułów', '/aplikacje-moduly', 'icon-clipboard', 'application', 9, NULL),
(55, 'Sprzęt komputerowy', '/computer', 'icon-print', 'computer', 9, NULL),
(56, 'Kopie zapasowe', '/kopiezapasowe', 'icon-archive', 'backup', 9, NULL),
(57, 'Strony www', '/sites', 'icon-website', 'website', 9, NULL),
(58, 'Rejestr transferów', '/data-transfers', 'glyphicon glyphicon-transfer', 'data_transfers', 10, NULL),
(59, 'Rejestr pobrań', '/data-transfers/pobrania', 'glyphicon glyphicon-transfer', 'data_transfers', 10, NULL),
(60, 'Rejestr udostępnienień', '/data-transfers/udostepnienia', 'glyphicon glyphicon-transfer', 'data_transfers', 10, NULL),
(61, 'Rejestr powierzeń', '/data-transfers/powierzenia', 'glyphicon glyphicon-transfer', 'data_transfers', 10, NULL),
(62, 'Podmioty', '/companies', 'fa fa-building-o', 'companies', 10, NULL),
(63, 'Pracownicy', '/company-employees', 'fa fa-building-o', 'companies', 10, NULL),
(64, 'Lista przepływów', '/flows', 'glyphicon glyphicon-transfer', 'data_transfers', 10, NULL),
(65, 'Wydarzenia', '/flows-events', 'glyphicon glyphicon-transfer', 'companies', 10, NULL),
(66, 'Role w przepływach', '/flows-roles', 'fa fa-users', 'companies', 10, NULL),
(67, 'Analiza ryzyka', '/risk-assessment', 'glyphicon glyphicon-transfer', 'risk-assessment', 11, NULL),
(68, 'Atrybuty', '/risk-assessment/index-attributes', 'glyphicon glyphicon-transfer', 'risk-assessment-attributes', 11, NULL),
(69, 'Podatności', '/risk-assessment/index-susceptibilites', 'glyphicon glyphicon-transfer', 'risk-assessment-susceptibilites', 11, NULL),
(70, 'Aktywa', '/risk-assessment/index-assets', 'glyphicon glyphicon-transfer', 'risk-assessment-assets', 11, NULL),
(71, 'Zagrożenia', '/risk-assessment/index-risks', 'glyphicon glyphicon-transfer', 'risk-assessment-risks', 11, NULL),
(72, 'Zabezpieczenia', '/risk-assessment/index-safeguards', 'glyphicon glyphicon-transfer', 'risk-assessment-risks', 11, NULL),
(73, 'Klasyfikacja', '/risk-assessment/index-classifications', 'glyphicon glyphicon-transfer', 'risk-assessment-risks', 11, NULL),
(74, 'Dane rejestracji', '/registration-data', 'glyphicon glyphicon-transfer', 'surveys', 12, NULL),
(75, 'Szkolenia', '/courses', 'fa fa-graduation-cap', 'courses', 13, NULL),
(76, 'Testy', '/exams', 'fa fa-graduation-cap', 'exams', 13, NULL),
(77, 'Kategorie szkoleń', '/course-categories', 'fa fa-list-ol', 'courses', 13, NULL),
(78, 'Kategorie testów', '/exam-categories', 'fa fa-list-ol', 'courses', 13, NULL),
(79, 'Ankiety', '/surveys', 'glyphicon glyphicon-transfer', 'surveys', 13, NULL),
(80, 'Ankiety - zarządzanie', '/surveys/manage', 'glyphicon glyphicon-th-list', 'risk-assessment-attributes', 13, NULL),
(81, 'Rejestr zdarzeń', '/events', 'icon-shuffle-2', 'events', 17, NULL),
(82, 'Firmy', '/eventscompanies', 'fa fa-building-o', 'events', 17, NULL),
(83, 'Rodzaje osób', '/eventspersonstypes', 'icon-cc-by', 'events', 17, NULL),
(84, 'Osoby', '/eventspersons', 'icon-users', 'events', 17, NULL),
(85, 'Pojazdy', '/eventscars', 'icon-traffic-cone', 'events', 17, NULL),
(86, 'Podstawowe informacje', '/config/company-information', 'icon-wrench', 'admin', 19, NULL),
(87, 'Logi z operacji', '/config/logi', 'icon-wrench', 'admin', 19, NULL),
(88, 'Logi z logowań', '/config/login-history', 'icon-key-inv', 'profile', 19, NULL),
(89, 'Zmiana hasła', '/home/zmianahasla', 'icon-key-inv', 'profile', 20, NULL),
(90, 'Połączone konta', '/shared-users', 'icon-key-inv', 'profile', 20, NULL),
(94, 'Name 1', '/registry-entries/index/registry_id/20', 'glyphicon glyphicon-cloud', 'registry', 8, NULL),
(98, 'Name 7', '/registry-entries/index/registry_id/26', 'glyphicon glyphicon-adjust', 'registry', 8, NULL);
SQL
);

db_query('ALTER TABLE registry ADD `icon` VARCHAR(100) NULL AFTER `is_visible`');
